site_name:        BioMedQuery.jl
site_author:      Isabel Restrepo
repo_url:         https://github.com/bcbi/BioMedQuery.jl
site_description: Julia connection to BioMedial Search APIs
site_author:      bcbi

theme:
  name: 'material'
  # logo: 'images/bcbi_logo.jpeg'

extra_css:
  - assets/Documenter.css

# extra_javascript:
#   - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#   - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - codehilite

  # - mdx_math

docs_dir: 'build'

pages:
- Home: index.md
- Examples:
  - Overview: examples.md
  - Pubmed Search and Save: examples/1_pubmed_search_and_save.md
  - MeSH/UMLS Map: examples/2_pubmed_mesh_to_umls_map.md
  - UMLS Semantic Filtering: examples/3_umls_semantic_occurrences.md
  - Export to Citations: examples/4_pubmed_export_citations.md
  - Load MEDLINE: examples/5_load_medline.md
- Manual:
  - Processes/Workflows: processes.md
  - PubMed: pubmed.md
  - Clinical Trials: ct.md
  - Database Utilities: dbutils.md
  - Library: library.md
